name: release
on:
  push:
    branches:
      - main
jobs:
  verify:
    uses: unional/.github/.github/workflows/yarn2-library-verify-linux.yml@main

  release:
    uses: unional/.github/.github/workflows/yarn2-library-release.yml@main
    needs: verify
    with:
      npm-token: ${{ secrets.NPM_TOKEN }}
