name: release
on:
  push:
    branches: [main]

jobs:
  code:
    uses: justland/.github/.github/workflows/pnpm-verify.yml@main
    with:
      os: '["ubuntu-latest"]'

  release:
    uses: justland/.github/.github/workflows/pnpm-release-changeset.yml@main
    needs: code
    secrets: inherit
